version: "3.7"
networks:
  tms_net:
    driver: bridge
    name: tms_net

  lb_server:
    image: haproxy:2.7
    container_name: lb_server
    hostname: lb_server
    restart: unless-stopped
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - tms_net
    ports:
      - 8001:80
    depends_on:
      tms_server:
        condition: service_healthy
