version: "3.7"

services:
  main_service:
    build:
      context: .
      dockerfile: Dockerfile.main
    container_name: main_service
    hostname: main_service
    restart: unless-stopped
    healthcheck:
      test: curl -f http://127.0.0.1:8000/healthcheck
      interval: 3s
      timeout: 2s
      retries: 5

  auth_service:
    build:
      context: .
      dockerfile: Dockerfile.main
    container_name: auth_service
    hostname: auth_service
    restart: unless-stopped
    healthcheck:
      test: curl -f http://127.0.0.1:8000/healthcheck
      interval: 3s
      timeout: 2s
      retries: 5

  user_service:
    build:
      context: .
      dockerfile: Dockerfile.user
    container_name: user_service
    hostname: user_service
    restart: unless-stopped
    healthcheck:
      test: curl -f http://127.0.0.1:8000/healthcheck
      interval: 3s
      timeout: 2s
      retries: 5
