name: Publish container images to GHCR

# on:
#   push:

on:
  release:
    types: [created, published]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract short commit SHA
        id: extract_sha
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and push Docker main image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: Dockerfile.main
          tags: |
            ghcr.io/extinctcoder/tms_micro:main
            ghcr.io/extinctcoder/tms_micro:main-${{ env.SHORT_SHA }}
            ghcr.io/extinctcoder/tms_micro:main-${{ github.event.release.tag_name }}

      - name: Build and push Docker auth image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.auth
          push: true
          tags: |
            ghcr.io/extinctcoder/tms_micro:auth
            ghcr.io/extinctcoder/tms_micro:auth-${{ env.SHORT_SHA }}
            ghcr.io/extinctcoder/tms_micro:auth-${{ github.event.release.tag_name }}

      - name: Build and push Docker user image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.user
          push: true
          tags: |
            ghcr.io/extinctcoder/tms_micro:user
            ghcr.io/extinctcoder/tms_micro:user-${{ env.SHORT_SHA }}
            ghcr.io/extinctcoder/tms_micro:user-${{ github.event.release.tag_name }}
