name: Publish container images to GHCR

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker main image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: Dockerfile.main
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main

    #   - name: Build and push Docker auth image
    #     uses: docker/build-push-action@v3
    #     with:
    #       context: .
    #       file: Dockerfile.auth
    #       push: true
    #       tags: extinctcoder/tms_micro:auth

    #   - name: Build and push Docker user image
    #     uses: docker/build-push-action@v3
    #     with:
    #       context: .
    #       file: Dockerfile.user
    #       push: true
    #       tags: extinctcoder/tms_micro:user
