name: Publish container images to GHCR

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha

      - name: Build and push Docker main image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.main
          push: true
          tags: ${{ steps.meta.outputs.tags }} zero
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker auth image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.auth
          push: true
          tags: ${{ steps.meta.outputs.tags }} auth
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker user image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.user
          push: true
          tags: ${{ steps.meta.outputs.tags }} user
          labels: ${{ steps.meta.outputs.labels }}
