name: Automated API Spec GEN

on:
  push:

jobs:
  generate_api_spec:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code repository
        id: code_checkout
        uses: actions/checkout@v4

      - name: Setup python environment
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      #   - name: Install the required python modules
      #     id: module_installation
      #     run: |
      #       python -m pip install --upgrade pip &&  pip install pipenv && pipenv lock && pipenv install --system --deploy && pipenv install --dev --system --deploy

      #   - name: Get the latest tag
      #     id: latest_tag
      #     uses: WyriHaximus/github-action-get-previous-tag@v1
      #     with:
      #       fallback: 0.0.0

      #   - name: Generate the api specification
      #     id: api_specification
      #     run: |
      #       cd src/auth_service && python openapi_doc.py && cd ../main_service && python openapi_doc.py && cd ../user_service && python openapi_doc.py && cd ../..
      - name: NewTag
        id: tag
        uses: JinoArch/get-latest-tag@latest

      - name: changelog
        id: changelog
        run: |
          echo "changelog=$(git log "${{ steps.tag.outputs.previousTag }}...${{ steps.tag.outputs.latestTag }}" --pretty=format:"- <http://github.com/rewards-guilds/kensho/commit/%H|%h> - %s\n" | awk '{print}' ORS=' ')" >> $GITHUB_OUTPUT

    #    - name: Commit the generaed changes
    #      uses: stefanzweifel/git-auto-commit-action@v5
    #      id: commit_changes
    #        with:
    #        commit_message: |
    #          docs: api spec generation based on ${{ steps.semvers.outputs.patch }}
    #        branch: main
