name: Automated semantic release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.11"

      # - name: Install pipenv for venv
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install pipenv

      # - name: Install dependencies
      #   run: |
      #     pipenv lock && pipenv install --system --deploy && pipenv install --dev --system --deploy

      # - name: Releasing new version with Python semantic release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     semantic-release version
      #     semantic-release publish
