name: Run micro-sevice unitest

# on:
#   pull_request:
#     types: [opened, synchronize]
on:
  push:

jobs:
  python_unitest:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code repository
        id: code_checkout
        uses: actions/checkout@v4

      - name: Setup python environment
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install the required python modules
        id: module_installation
        run: |
          python -m pip install --upgrade pip && pip install pipenv && pipenv lock && pipenv install --system --deploy && pipenv install --dev --system --deploy

      - name: Run unit tests on the test server
        id: run_pytest
        run: |
          pytest
