name: Automated MicroService Unit TEST

on:
  pull_request:
    types: [opened]

jobs:
  AutomatedPyTest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      pull-requests: write

    steps:
      - name: Checkout code repository
        id: code_checkout
        uses: actions/checkout@v4

      - name: Setup python environment
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install the required python modules
        id: module_installation
        run: |
          python -m pip install --upgrade pip && pip install pipenv && pipenv lock && pipenv install --system --deploy && pipenv install --dev --system --deploy

      - name: Run unit tests on the test server
        id: run_pytest
        run: |
          pytest --cov --junitxml=pytest.xml  --cov-report=term-missing:skip-covered | tee pytest-coverage.txt

      - name: Comment coverage report
        id: coverage_report
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
