name: Run micro-sevice unitest

on: push
#   pull_request:
#     types: [opened, synchronize]

jobs:
  python_unitest:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pipenv for venv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: |
          pipenv lock && pipenv install --system --deploy && pipenv install --dev --system --deploy

      - name: Run unit tests
        run: |
          pytest
